### PR TITLE
Relase for Fluentd v0.12.x

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
Could you create branch for Fluentd v0.12.x after merge this PR?

**Comment by bungoume** [comment]
v1.1.0 runs with fluentd v0.14 on my system.

I'm planning to do like this.

* <1.2.0 support fluentd v0.12 - v0.14
* 1.2.x support only v0.14-

**Comment by okkez** [comment]
OK, thank you for telling your plan.

**Comment by okkez** [comment]
FYI: fluent-plugin-ua-parser v1.1.0 runs with Fluentd v0.14.x but using compatibility layer.
It is not Fluentd v0.14 API.

**Pull request closed without merging**
